### ISSUE TITLE
Should be possible to update hosts file within a pi-hole docker container

### ISSUE THREAD

**Issue by ax42** [farsonic/unifi-to-hosts-mapping#7]

**Comment by ax42** [comment]
Closed in #6 by allowing the user to choose which hosts file to edit

**Comment by shanelord01** [comment]
I'm having this issue, and even if I set -f or --hostfile to local.list, I still get the "You need root permissions to write to /etc/hosts - skipping!" error.

I have the container set to high priveledge also.
