### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by ndng28** [farsonic/unifi-to-hosts-mapping#8]
Hello,

I am running into this error
> Traceback (most recent call last):
>   File "./client-mapping.py", line 48, in <module>
>     c = Controller(controllerIP, userName, password, "8443", "v4", "default")
>   File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 92, in __init__
>     self._login(version)
>   File "/usr/local/lib/python2.7/dist-packages/unifi/controller.py", line 163, in _login
>     self.opener.open(login_url, params).read()
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
>     context=self._context)
>   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>     raise URLError(err)
> urllib2.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)>
> Exception urllib2.URLError: URLError(SSLError(1, u'[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)'),) in <bound method Controller.__del__ of <unifi.controller.Controller instance at 0x7f5e35b52488>> ignored

Any ideas?

Thanks

**Comment by ax42** [comment]
This is due to the unifi controller python package using TLS1. I fixed it by editing that file manually to specify TLSv2. Crude but it works. 

The file you need to edit is shown in your error message: /usr/local/lib/..../controller.py

Note if you update the unifi package you will lose the fix.

**Comment by farsonic** [comment]
Thanks for the quick fix to this :)

**Comment by ndng28** [comment]
Thanks!
